name: 'My First Github Actions'

on: push # push 이벤트에 반응

env: 
  PRESET_VALUE: "This is the value preset"

jobs:
  first_job:
      name: 'First Job'
      runs-on: ubuntu-latest # 가장 최신 버전의 우분투에서 깃헙 액션이 동작

      steps: # 여러 개의 step 지정 가능
        - name: Set environment variable 1
          shell: bash
          run: |
            echo "VAR1='This is the value from the step 1'" >> $GITHUB_ENV
        
        - name: Set environment variable 2
          shell: pwsh
          run: |
            echo "VAR2='This is the value from the step 2'" | `
              Out-File -FilePath $env:GITHUB_ENV -Encoding UTF-8 -Append
          
        -name: Check environment variables
          shell: bash
          run: |
            echo "preset value: ${{ env.PRESET_VALUE }}"
            echo "value1: $VAR1"
            echo "value2: $VAR2"
